apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  name: argocd-devteam-b-projects
  namespace: devteam-b
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  project: devteam-b
  #name: argocd-devteam-b-projects
  url: https://github.com/tppalani/devteam-b.git
  type: git
