apiVersion: v1
kind: Secret
metadata:
  name: argocd-devteam-b-projects
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  project: devteam-b
  name: argocd-devteam-b-projects
  url: https://github.com/tppalani/devteam-b.git
